# Crie um programa que leia dois números e mostre a soma entre eles. Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.
algo = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(algo))
print('É alfabético?', algo.isalpha())
print('É numérico?', algo.isnumeric())
print('Só tem espaços?', algo.isspace())
print('É alfanumérico?', algo.isalnum())
print('Está em maiúsculas?', algo.isupper())
print('Está em minúsculas?', algo.islower())
print('Está capitalizada?', algo.istitle())
